using System.Text;
using Microsoft.CodeAnalysis.CSharp;

namespace MelangeDB.CodeGen;

/// <summary>
/// Emits the typed client bindings from a parsed manifest, into the <c>MelangeDB.Types</c>
/// namespace — the shape <c>spacetime generate</c> trained a porting hand to expect:
/// <c>conn.Db.Table.OnInsert</c>, <c>conn.Db.Table.Column.Find(...)</c>,
/// <c>conn.Reducers.NameAsync(...)</c>. Emitted code stays thin; the cache mechanics live in
/// MelangeDB.Client behind <c>IClientRowCodec&lt;T&gt;</c>.
/// </summary>
internal static class ClientEmitter
{
    private const string Header = """
        // <auto-generated/>
        // Generated by MelangeDB.CodeGen from melange-schema.json. Changes will be overwritten.
        #nullable disable
        #pragma warning disable

        """;

    /// <summary>Emits one table's row struct, codec, handle, and column accessors.</summary>
    public static string EmitTable(ClientTableModel table)
    {
        var builder = new StringBuilder(Header);
        builder.AppendLine("namespace MelangeDB.Types");
        builder.AppendLine("{");
        EmitRowStruct(builder, table);
        EmitCodec(builder, table);
        EmitHandle(builder, table);
        foreach (var column in table.Columns.Items)
        {
            if (column.HasAccessor)
                EmitAccessor(builder, table, column);
        }

        builder.AppendLine("}");
        return builder.ToString();
    }

    /// <summary>Emits the enums, the Db view, the reducer stubs, and the connection wrapper.</summary>
    public static string EmitModel(ClientSchemaModel schema)
    {
        var builder = new StringBuilder(Header);
        builder.AppendLine("namespace MelangeDB.Types");
        builder.AppendLine("{");
        foreach (var declaration in schema.Enums.Items)
        {
            builder.AppendLine($"    /// <summary>Mirrors the server's '{declaration.Name}' enum, per the schema manifest.</summary>");
            builder.AppendLine($"    public enum {declaration.Name} : {ClrType(declaration.Underlying, enumName: null)}");
            builder.AppendLine("    {");
            foreach (var member in declaration.Members.Items)
                builder.AppendLine($"        {member.Name} = {member.Value},");
            builder.AppendLine("    }");
            builder.AppendLine();
        }

        builder.AppendLine("    /// <summary>The schema these bindings were generated from.</summary>");
        builder.AppendLine("    public static class MelangeSchema");
        builder.AppendLine("    {");
        builder.AppendLine("        /// <summary>The manifest's schema hash; compare against the server module's to surface drift.</summary>");
        builder.AppendLine($"        public const string Hash = {Literal(schema.SchemaHash)};");
        builder.AppendLine();
        builder.AppendLine($"        public const string Module = {Literal(schema.Module)};");
        builder.AppendLine("    }");
        builder.AppendLine();

        builder.AppendLine("    /// <summary>Typed table handles over one connection's merged caches.</summary>");
        builder.AppendLine("    public sealed class MelangeDbView");
        builder.AppendLine("    {");
        builder.AppendLine("        private readonly global::MelangeDB.Client.ClientCacheRegistry _caches;");
        builder.AppendLine();
        builder.AppendLine("        internal MelangeDbView(global::MelangeDB.Client.ClientCacheRegistry caches) => _caches = caches;");
        foreach (var table in schema.Tables.Items)
        {
            builder.AppendLine();
            builder.AppendLine($"        public {table.TypeName}TableHandle {table.TypeName} => new {table.TypeName}TableHandle(_caches);");
        }

        builder.AppendLine("    }");
        builder.AppendLine();

        builder.AppendLine("    /// <summary>One typed stub per client-callable reducer; the returned LSN is the commit (0 when nothing was written).</summary>");
        builder.AppendLine("    public sealed class MelangeReducers");
        builder.AppendLine("    {");
        builder.AppendLine("        private readonly global::MelangeDB.Client.MelangeClient _client;");
        builder.AppendLine();
        builder.AppendLine("        internal MelangeReducers(global::MelangeDB.Client.MelangeClient client) => _client = client;");
        foreach (var reducer in schema.Reducers.Items)
        {
            var parameters = string.Concat(reducer.Parameters.Items.Select(p => $"{ParameterClrType(p)} {ParameterName(p.Name)}, "));
            var arguments = string.Join(", ", reducer.Parameters.Items.Select(p => ParameterName(p.Name)));
            builder.AppendLine();
            builder.AppendLine($"        public global::System.Threading.Tasks.Task<ulong> {reducer.Name}Async({parameters}global::System.Threading.CancellationToken cancellationToken = default) =>");
            builder.AppendLine(reducer.Parameters.Length == 0
                ? $"            _client.CallReducerAsync({Literal(reducer.Name)}, null, cancellationToken);"
                : $"            _client.CallReducerAsync({Literal(reducer.Name)}, new object[] {{ {arguments} }}, cancellationToken);");
        }

        builder.AppendLine("    }");
        builder.AppendLine();

        builder.AppendLine("    /// <summary>");
        builder.AppendLine("    /// The typed connection: Db for cached rows and events, Reducers for calls, Client for");
        builder.AppendLine("    /// everything the raw API still owns (connect, reconnect, untyped subscriptions).");
        builder.AppendLine("    /// </summary>");
        builder.AppendLine("    public sealed partial class MelangeConnection");
        builder.AppendLine("    {");
        builder.AppendLine("        public MelangeConnection(global::MelangeDB.Client.MelangeClient client)");
        builder.AppendLine("        {");
        builder.AppendLine("            Client = client ?? throw new global::System.ArgumentNullException(nameof(client));");
        builder.AppendLine("            Caches = new global::MelangeDB.Client.ClientCacheRegistry(client);");
        builder.AppendLine("            Db = new MelangeDbView(Caches);");
        builder.AppendLine("            Reducers = new MelangeReducers(client);");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        public global::MelangeDB.Client.MelangeClient Client { get; }");
        builder.AppendLine();
        builder.AppendLine("        public global::MelangeDB.Client.ClientCacheRegistry Caches { get; }");
        builder.AppendLine();
        builder.AppendLine("        public MelangeDbView Db { get; }");
        builder.AppendLine();
        builder.AppendLine("        public MelangeReducers Reducers { get; }");
        builder.AppendLine();
        builder.AppendLine("        /// <summary>The identity this connection authenticated as — what tells my rows apart from everyone else's. Known once connected.</summary>");
        builder.AppendLine("        public global::MelangeDB.Identity Identity => Client.Identity;");
        builder.AppendLine();
        builder.AppendLine("        /// <summary>The schema hash these bindings were generated from — the drift detector.</summary>");
        builder.AppendLine("        public string SchemaHash => MelangeSchema.Hash;");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void EmitRowStruct(StringBuilder builder, ClientTableModel table)
    {
        builder.AppendLine($"    /// <summary>One row of table '{table.TableName}', as the wire carries it to clients.</summary>");
        builder.AppendLine($"    public partial struct {table.TypeName}");
        builder.AppendLine("    {");
        foreach (var column in table.Columns.Items)
            builder.AppendLine($"        public {ClrType(column.Kind, column.EnumName)} {column.Name};");
        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static void EmitCodec(StringBuilder builder, ClientTableModel table)
    {
        builder.AppendLine($"    /// <summary>Decodes '{table.TableName}' rows straight from the wire's row bytes: positional, no dictionary, no boxing.</summary>");
        builder.AppendLine($"    public sealed class {table.TypeName}RowCodec : global::MelangeDB.Client.IClientRowCodec<{table.TypeName}>");
        builder.AppendLine("    {");
        builder.AppendLine($"        public static readonly {table.TypeName}RowCodec Instance = new {table.TypeName}RowCodec();");
        builder.AppendLine();
        builder.AppendLine("        // The shape these bindings were generated from, compared against the server's");
        builder.AppendLine("        // descriptor once per subscription. Order is contract: the row bytes are positional.");
        builder.AppendLine("        private static readonly global::MelangeDB.Protocol.WireColumn[] Shape = new global::MelangeDB.Protocol.WireColumn[]");
        builder.AppendLine("        {");
        foreach (var column in table.Columns.Items)
            builder.AppendLine($"            new global::MelangeDB.Protocol.WireColumn({Literal(column.Name)}, global::MelangeDB.ColumnKind.{column.Kind}),");
        builder.AppendLine("        };");
        builder.AppendLine();
        builder.AppendLine($"        public string TableName => {Literal(table.TableName)};");
        builder.AppendLine();
        builder.AppendLine("        public global::System.Collections.Generic.IReadOnlyList<global::MelangeDB.Protocol.WireColumn> Columns => Shape;");
        builder.AppendLine();
        builder.AppendLine($"        public {table.TypeName} DecodeRow(global::System.ReadOnlySpan<byte> data)");
        builder.AppendLine("        {");
        builder.AppendLine("            var reader = new global::MelangeDB.RowReader(data);");
        builder.AppendLine($"            var row = default({table.TypeName});");
        foreach (var column in table.Columns.Items)
        {
            var read = $"reader.Read{column.Kind}()";
            builder.AppendLine(column.EnumName is null
                ? $"            row.{column.Name} = {read};"
                : $"            row.{column.Name} = ({column.EnumName}){read};");
        }

        builder.AppendLine("            return row;");
        builder.AppendLine("        }");
        builder.AppendLine();
        var primaryKey = table.PrimaryKey;
        builder.AppendLine($"        public byte[] EncodePrimaryKey(in {table.TypeName} row) =>");
        builder.AppendLine($"            {KeyEncode(primaryKey, $"row.{primaryKey.Name}")}.ToArray();");
        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static void EmitHandle(StringBuilder builder, ClientTableModel table)
    {
        var handle = $"{table.TypeName}TableHandle";
        builder.AppendLine($"    /// <summary>Typed access to the '{table.TableName}' client cache: rows, events, lookups, subscriptions.</summary>");
        builder.AppendLine($"    public readonly struct {handle}");
        builder.AppendLine("    {");
        builder.AppendLine("        private readonly global::MelangeDB.Client.ClientCacheRegistry _caches;");
        builder.AppendLine($"        private readonly global::MelangeDB.Client.ClientCache<{table.TypeName}> _cache;");
        builder.AppendLine();
        builder.AppendLine($"        public {handle}(global::MelangeDB.Client.ClientCacheRegistry caches)");
        builder.AppendLine("        {");
        builder.AppendLine("            _caches = caches;");
        builder.AppendLine($"            _cache = caches.GetOrAdd({table.TypeName}RowCodec.Instance);");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        /// <summary>The merged cache under this handle, for advanced use.</summary>");
        builder.AppendLine($"        public global::MelangeDB.Client.ClientCache<{table.TypeName}> Cache => _cache;");
        builder.AppendLine();
        builder.AppendLine($"        public event global::System.Action<{table.TypeName}> OnInsert");
        builder.AppendLine("        {");
        builder.AppendLine("            add => _cache.OnInsert += value;");
        builder.AppendLine("            remove => _cache.OnInsert -= value;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine($"        public event global::System.Action<{table.TypeName}, {table.TypeName}> OnUpdate");
        builder.AppendLine("        {");
        builder.AppendLine("            add => _cache.OnUpdate += value;");
        builder.AppendLine("            remove => _cache.OnUpdate -= value;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine($"        public event global::System.Action<{table.TypeName}> OnDelete");
        builder.AppendLine("        {");
        builder.AppendLine("            add => _cache.OnDelete += value;");
        builder.AppendLine("            remove => _cache.OnDelete -= value;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        /// <summary>Locally cached row count — the rows this client's subscriptions cover, not the table's.</summary>");
        builder.AppendLine("        public int Count => _cache.Count;");
        builder.AppendLine();
        builder.AppendLine("        /// <summary>A snapshot of the locally cached rows.</summary>");
        builder.AppendLine($"        public global::System.Collections.Generic.IReadOnlyList<{table.TypeName}> Iter() => _cache.Rows;");
        builder.AppendLine();
        builder.AppendLine($"        /// <summary>Subscribes to every row of '{table.TableName}'.</summary>");
        builder.AppendLine($"        public global::System.Threading.Tasks.Task<global::MelangeDB.Client.TypedSubscription<{table.TypeName}>> SubscribeAllAsync(global::System.Threading.CancellationToken cancellationToken = default) =>");
        builder.AppendLine($"            _caches.SubscribeAsync({table.TypeName}RowCodec.Instance, {Literal($"SELECT * FROM {table.TableName}")}, null, cancellationToken);");
        foreach (var column in table.Columns.Items)
        {
            if (!column.HasAccessor)
                continue;
            builder.AppendLine();
            builder.AppendLine($"        public {table.TypeName}{column.Name}Accessor {column.Name} => new {table.TypeName}{column.Name}Accessor(_caches, _cache);");
        }

        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static void EmitAccessor(StringBuilder builder, ClientTableModel table, ClientColumnModel column)
    {
        var accessor = $"{table.TypeName}{column.Name}Accessor";
        var row = table.TypeName;
        var clr = ClrType(column.Kind, column.EnumName);
        builder.AppendLine($"    /// <summary>Typed lookups and subscriptions on '{table.TableName}.{column.Name}', against the local cache and the four query shapes.</summary>");
        builder.AppendLine($"    public readonly struct {accessor}");
        builder.AppendLine("    {");
        builder.AppendLine("        private readonly global::MelangeDB.Client.ClientCacheRegistry _caches;");
        builder.AppendLine($"        private readonly global::MelangeDB.Client.ClientCache<{row}> _cache;");
        builder.AppendLine();
        builder.AppendLine($"        public {accessor}(global::MelangeDB.Client.ClientCacheRegistry caches, global::MelangeDB.Client.ClientCache<{row}> cache)");
        builder.AppendLine("        {");
        builder.AppendLine("            _caches = caches;");
        builder.AppendLine("            _cache = cache;");
        builder.AppendLine("        }");

        if (column.IsPrimaryKey)
        {
            builder.AppendLine();
            builder.AppendLine("        /// <summary>Finds the cached row with this primary key, or null when no subscription covers it.</summary>");
            builder.AppendLine($"        public {row}? Find({clr} key) =>");
            builder.AppendLine($"            _cache.TryFind({KeyEncode(column, "key")}.ToArray(), out var row) ? row : ({row}?)null;");
        }
        else if (column.IsUnique)
        {
            builder.AppendLine();
            builder.AppendLine("        /// <summary>Finds the cached row with this unique value, or null. Scans the local cache.</summary>");
            builder.AppendLine($"        public {row}? Find({clr} value)");
            builder.AppendLine("        {");
            builder.AppendLine($"            var key = {KeyEncode(column, "value")};");
            builder.AppendLine("            foreach (var row in _cache.Rows)");
            builder.AppendLine("            {");
            builder.AppendLine($"                if ({KeyEncode(column, $"row.{column.Name}")} == key)");
            builder.AppendLine("                    return row;");
            builder.AppendLine("            }");
            builder.AppendLine();
            builder.AppendLine($"            return ({row}?)null;");
            builder.AppendLine("        }");
        }
        else
        {
            builder.AppendLine();
            builder.AppendLine("        /// <summary>The cached rows with this value. Scans the local cache.</summary>");
            builder.AppendLine($"        public global::System.Collections.Generic.List<{row}> Filter({clr} value)");
            builder.AppendLine("        {");
            builder.AppendLine($"            var key = {KeyEncode(column, "value")};");
            builder.AppendLine($"            var rows = new global::System.Collections.Generic.List<{row}>();");
            builder.AppendLine("            foreach (var row in _cache.Rows)");
            builder.AppendLine("            {");
            builder.AppendLine($"                if ({KeyEncode(column, $"row.{column.Name}")} == key)");
            builder.AppendLine("                    rows.Add(row);");
            builder.AppendLine("            }");
            builder.AppendLine();
            builder.AppendLine("            return rows;");
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine("        /// <summary>The cached rows in [low, high], compared exactly as the server compares — by encoded key.</summary>");
            builder.AppendLine($"        public global::System.Collections.Generic.List<{row}> Filter({clr} low, {clr} high)");
            builder.AppendLine("        {");
            builder.AppendLine($"            var lowKey = {KeyEncode(column, "low")};");
            builder.AppendLine($"            var highKey = {KeyEncode(column, "high")};");
            builder.AppendLine($"            var rows = new global::System.Collections.Generic.List<{row}>();");
            builder.AppendLine("            foreach (var row in _cache.Rows)");
            builder.AppendLine("            {");
            builder.AppendLine($"                var candidate = {KeyEncode(column, $"row.{column.Name}")};");
            builder.AppendLine("                if (candidate.CompareTo(lowKey) >= 0 && candidate.CompareTo(highKey) <= 0)");
            builder.AppendLine("                    rows.Add(row);");
            builder.AppendLine("            }");
            builder.AppendLine();
            builder.AppendLine("            return rows;");
            builder.AppendLine("        }");
        }

        // Subscription helpers: the equality and range shapes, plus the typed rescope that keeps
        // the terrain-streaming pattern a method call. Not every shape the SQL subset supports —
        // whole-table and not-default are deliberately left on the untyped API (CLIENT-BINDINGS.md).
        var equalitySql = Literal($"SELECT * FROM {table.TableName} WHERE {column.Name} = :p");
        var rangeSql = Literal($"SELECT * FROM {table.TableName} WHERE {column.Name} BETWEEN :lo AND :hi");
        builder.AppendLine();
        builder.AppendLine($"        /// <summary>Subscribes to rows where '{column.Name}' equals the value.</summary>");
        builder.AppendLine($"        public global::System.Threading.Tasks.Task<global::MelangeDB.Client.TypedSubscription<{row}>> SubscribeAsync({clr} value, global::System.Threading.CancellationToken cancellationToken = default) =>");
        builder.AppendLine($"            _caches.SubscribeAsync({table.TypeName}RowCodec.Instance, {equalitySql}, EqualityParameters(value), cancellationToken);");
        builder.AppendLine();
        builder.AppendLine($"        /// <summary>Re-scopes a subscription created by <see cref=\"SubscribeAsync({EscapeCref(clr)}, global::System.Threading.CancellationToken)\"/> to a new value, reconciled as a diff.</summary>");
        builder.AppendLine($"        public global::System.Threading.Tasks.Task RescopeAsync(global::MelangeDB.Client.TypedSubscription<{row}> subscription, {clr} value, global::System.Threading.CancellationToken cancellationToken = default) =>");
        builder.AppendLine("            subscription.RescopeAsync(EqualityParameters(value), cancellationToken);");
        builder.AppendLine();
        builder.AppendLine($"        /// <summary>Subscribes to rows where '{column.Name}' is in [low, high].</summary>");
        builder.AppendLine($"        public global::System.Threading.Tasks.Task<global::MelangeDB.Client.TypedSubscription<{row}>> SubscribeRangeAsync({clr} low, {clr} high, global::System.Threading.CancellationToken cancellationToken = default) =>");
        builder.AppendLine($"            _caches.SubscribeAsync({table.TypeName}RowCodec.Instance, {rangeSql}, RangeParameters(low, high), cancellationToken);");
        builder.AppendLine();
        builder.AppendLine($"        /// <summary>Re-scopes a subscription created by <see cref=\"SubscribeRangeAsync({EscapeCref(clr)}, {EscapeCref(clr)}, global::System.Threading.CancellationToken)\"/> to a new window, reconciled as a diff.</summary>");
        builder.AppendLine($"        public global::System.Threading.Tasks.Task RescopeRangeAsync(global::MelangeDB.Client.TypedSubscription<{row}> subscription, {clr} low, {clr} high, global::System.Threading.CancellationToken cancellationToken = default) =>");
        builder.AppendLine("            subscription.RescopeAsync(RangeParameters(low, high), cancellationToken);");
        builder.AppendLine();
        builder.AppendLine($"        private static global::System.Collections.Generic.Dictionary<string, object> EqualityParameters({clr} value) =>");
        builder.AppendLine($"            new global::System.Collections.Generic.Dictionary<string, object> {{ [\"p\"] = {WireValue(column, "value")} }};");
        builder.AppendLine();
        builder.AppendLine($"        private static global::System.Collections.Generic.Dictionary<string, object> RangeParameters({clr} low, {clr} high) =>");
        builder.AppendLine($"            new global::System.Collections.Generic.Dictionary<string, object> {{ [\"lo\"] = {WireValue(column, "low")}, [\"hi\"] = {WireValue(column, "high")} }};");
        builder.AppendLine("    }");
        builder.AppendLine();
    }

    /// <summary>The value as the parameter map carries it: enums narrow to their underlying integer.</summary>
    private static string WireValue(ClientColumnModel column, string access) =>
        column.EnumName is null ? access : $"({ClrType(column.Kind, enumName: null)}){access}";

    private static string KeyEncode(ClientColumnModel column, string access) =>
        $"global::MelangeDB.KeyCodec.Encode{column.Kind}({(column.EnumName is null ? access : $"({ClrType(column.Kind, enumName: null)}){access}")})";

    private static string ClrType(WireKind kind, string? enumName)
    {
        if (enumName is not null)
            return enumName;
        return kind switch
        {
            WireKind.Bool => "bool",
            WireKind.Int8 => "sbyte",
            WireKind.UInt8 => "byte",
            WireKind.Int16 => "short",
            WireKind.UInt16 => "ushort",
            WireKind.Int32 => "int",
            WireKind.UInt32 => "uint",
            WireKind.Int64 => "long",
            WireKind.UInt64 => "ulong",
            WireKind.Float32 => "float",
            WireKind.Float64 => "double",
            WireKind.String => "string",
            WireKind.Bytes => "byte[]",
            WireKind.Identity => "global::MelangeDB.Identity",
            WireKind.Timestamp => "global::MelangeDB.Timestamp",
            _ => throw new InvalidOperationException($"Kind {kind} is not client-visible."),
        };
    }

    private static string ParameterClrType(ClientParameterModel parameter)
    {
        var element = ClrType(parameter.Kind, parameter.EnumName);
        return parameter.IsArray ? element + "[]" : element;
    }

    /// <summary>Parameter names come from the manifest; a C# keyword gets the verbatim prefix.</summary>
    private static string ParameterName(string name) =>
        SyntaxFacts.GetKeywordKind(name) == SyntaxKind.None && SyntaxFacts.GetContextualKeywordKind(name) == SyntaxKind.None
            ? name
            : "@" + name;

    private static string EscapeCref(string type) => type.Replace('<', '{').Replace('>', '}');

    private static string Literal(string value)
    {
        var builder = new StringBuilder("\"");
        foreach (var c in value)
        {
            switch (c)
            {
                case '\\':
                    builder.Append("\\\\");
                    break;
                case '"':
                    builder.Append("\\\"");
                    break;
                default:
                    builder.Append(c);
                    break;
            }
        }

        return builder.Append('"').ToString();
    }
}
