using System.Text;

namespace MelangeDB.CodeGen;

/// <summary>Emits the generated sources: per-table codec and accessors, and the per-assembly model.</summary>
internal static class Emitter
{
    private const string Header = """
        // <auto-generated/>
        // Generated by MelangeDB.CodeGen. Changes will be overwritten.
        #nullable disable
        #pragma warning disable

        """;

    public static string EmitTable(TableModel table)
    {
        var builder = new StringBuilder(Header);
        builder.AppendLine("namespace MelangeDB.Generated");
        builder.AppendLine("{");
        EmitCodec(builder, table);
        EmitAccessors(builder, table);
        builder.AppendLine("}");
        return builder.ToString();
    }

    public static string EmitModel(TableModel[] tables, ReducerModel[] reducers)
    {
        var builder = new StringBuilder(Header);
        builder.AppendLine("[assembly: global::MelangeDB.Core.MelangeGeneratedModel(typeof(global::MelangeDB.Generated.MelangeModel))]");
        builder.AppendLine();
        builder.AppendLine("namespace MelangeDB.Generated");
        builder.AppendLine("{");
        builder.AppendLine("    /// <summary>This assembly's tables and reducers, discovered at compile time.</summary>");
        builder.AppendLine("    internal sealed class MelangeModel : global::MelangeDB.Core.IMelangeModel");
        builder.AppendLine("    {");
        builder.AppendLine("        public global::System.Collections.Generic.IReadOnlyList<global::MelangeDB.Core.TableSchema> Tables() =>");
        builder.AppendLine("            new global::MelangeDB.Core.TableSchema[]");
        builder.AppendLine("            {");
        foreach (var table in tables)
            builder.AppendLine($"                global::MelangeDB.Generated.{table.TypeName}Codec.BuildSchema(),");
        builder.AppendLine("            };");
        builder.AppendLine();
        builder.AppendLine("        public global::System.Collections.Generic.IReadOnlyList<global::MelangeDB.Core.ReducerDescriptor> Reducers() =>");
        builder.AppendLine("            new global::MelangeDB.Core.ReducerDescriptor[]");
        builder.AppendLine("            {");
        var tableTypeNames = tables.ToDictionary(static t => t.TypeFqn, static t => t.TypeName);
        foreach (var reducer in reducers)
            EmitDescriptor(builder, reducer, tableTypeNames);
        builder.AppendLine("            };");
        builder.AppendLine("    }");
        builder.AppendLine("}");

        if (tables.Length > 0)
        {
            // Global namespace, so ctx.Db.<Table> resolves everywhere in the assembly with no
            // using directive. The class is internal; nothing leaks across assemblies.
            builder.AppendLine();
            builder.AppendLine("/// <summary>Typed table accessors on <c>ctx.Db</c>.</summary>");
            builder.AppendLine("internal static class MelangeDbGeneratedAccessors");
            builder.AppendLine("{");
            builder.AppendLine("    extension(global::MelangeDB.IDbView db)");
            builder.AppendLine("    {");
            foreach (var table in tables)
            {
                builder.AppendLine($"        public global::MelangeDB.Generated.{table.TypeName}Handle {table.TypeName} =>");
                builder.AppendLine($"            new global::MelangeDB.Generated.{table.TypeName}Handle(db);");
            }

            builder.AppendLine("    }");
            builder.AppendLine("}");
        }

        return builder.ToString();
    }

    private static void EmitCodec(StringBuilder builder, TableModel table)
    {
        var row = table.TypeFqn;
        builder.AppendLine($"    /// <summary>Generated serializer for table '{table.TableName}': row format v1, no reflection, no boxing.</summary>");
        builder.AppendLine($"    internal sealed class {table.TypeName}Codec : global::MelangeDB.Core.RowCodec<{row}>");
        builder.AppendLine("    {");
        builder.AppendLine($"        public static readonly {table.TypeName}Codec Instance = new {table.TypeName}Codec();");
        builder.AppendLine();

        EmitBuildSchema(builder, table);

        builder.AppendLine($"        public override byte[] Serialize(in {row} row)");
        builder.AppendLine("        {");
        builder.AppendLine("            var writer = new global::MelangeDB.Core.RowWriter(64);");
        foreach (var column in table.Columns.Items)
            builder.AppendLine($"            writer.Write{column.Kind}({CastToWire(column, $"row.{column.Name}")});");
        builder.AppendLine("            return writer.ToArray();");
        builder.AppendLine("        }");
        builder.AppendLine();

        builder.AppendLine($"        public override {row} Deserialize(global::System.ReadOnlySpan<byte> data)");
        builder.AppendLine("        {");
        builder.AppendLine("            var reader = new global::MelangeDB.Core.RowReader(data);");
        builder.AppendLine($"            var row = default({row});");
        foreach (var column in table.Columns.Items)
            builder.AppendLine($"            row.{column.Name} = {CastFromWire(column, $"reader.Read{column.Kind}()")};");
        builder.AppendLine("            return row;");
        builder.AppendLine("        }");
        builder.AppendLine();

        var primaryKey = table.Columns.Items.First(static c => c.IsPrimaryKey);
        builder.AppendLine($"        public override global::MelangeDB.RowKey EncodePrimaryKey(in {row} row) =>");
        builder.AppendLine($"            {KeyEncode(primaryKey, $"row.{primaryKey.Name}")};");
        builder.AppendLine();

        builder.AppendLine($"        public override global::MelangeDB.RowKey? EncodeColumn(string column, in {row} row)");
        builder.AppendLine("        {");
        builder.AppendLine("            switch (column)");
        builder.AppendLine("            {");
        foreach (var column in table.Columns.Items)
        {
            if (!column.IsKeyEncodable || !(column.IsPrimaryKey || column.HasIndexAccessor))
                continue;
            var access = $"row.{column.Name}";
            builder.AppendLine(column.Kind is WireKind.String or WireKind.Bytes
                ? $"                case \"{column.Name}\": return {access} is null ? default(global::MelangeDB.RowKey?) : {KeyEncode(column, access)};"
                : $"                case \"{column.Name}\": return {KeyEncode(column, access)};");
        }

        builder.AppendLine($"                default: throw new global::System.ArgumentException($\"Table '{table.TableName}' has no key-encodable column '{{column}}'.\", nameof(column));");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();

        builder.AppendLine($"        public override void AssignAutoInc(ref {row} row, global::MelangeDB.Core.AutoIncStage stage, global::MelangeDB.TableId table)");
        builder.AppendLine("        {");
        foreach (var column in table.Columns.Items)
        {
            if (!column.IsAutoInc)
                continue;
            if (column.Kind == WireKind.UInt64)
            {
                builder.AppendLine($"            if (row.{column.Name} == 0UL)");
                builder.AppendLine($"                row.{column.Name} = stage.Allocate(table);");
                builder.AppendLine("            else");
                builder.AppendLine($"                stage.ObserveExplicit(table, row.{column.Name});");
            }
            else
            {
                builder.AppendLine($"            if (row.{column.Name} == 0L)");
                builder.AppendLine($"                row.{column.Name} = (long)stage.Allocate(table);");
                builder.AppendLine($"            else if (row.{column.Name} > 0L)");
                builder.AppendLine($"                stage.ObserveExplicit(table, (ulong)row.{column.Name});");
            }
        }

        builder.AppendLine("        }");
        builder.AppendLine("    }");
        builder.AppendLine();
    }

    private static void EmitBuildSchema(StringBuilder builder, TableModel table)
    {
        var row = table.TypeFqn;
        builder.AppendLine("        public static global::MelangeDB.Core.TableSchema BuildSchema() =>");
        builder.AppendLine("            new global::MelangeDB.Core.TableSchema(");
        builder.AppendLine($"                typeof({row}),");
        builder.AppendLine($"                {Literal(table.TableName)},");
        builder.AppendLine("                new global::MelangeDB.Core.ColumnSchema[]");
        builder.AppendLine("                {");
        foreach (var column in table.Columns.Items)
        {
            builder.AppendLine("                    new global::MelangeDB.Core.ColumnSchema");
            builder.AppendLine("                    {");
            builder.AppendLine($"                        Name = {Literal(column.Name)},");
            builder.AppendLine($"                        ClrType = typeof({column.ClrFqn}),");
            builder.AppendLine($"                        Kind = global::MelangeDB.Core.ColumnKind.{column.Kind},");
            builder.AppendLine($"                        IsEnum = {(column.IsEnum ? "true" : "false")},");
            builder.AppendLine($"                        IsPrimaryKey = {(column.IsPrimaryKey ? "true" : "false")},");
            builder.AppendLine($"                        IsAutoInc = {(column.IsAutoInc ? "true" : "false")},");
            builder.AppendLine($"                        IsUnique = {(column.IsUnique ? "true" : "false")},");
            builder.AppendLine($"                        IsIndexed = {(column.IsIndexed ? "true" : "false")},");
            builder.AppendLine($"                        IsServerOnly = {(column.IsServerOnly ? "true" : "false")},");
            builder.AppendLine($"                        GetValue = static row => (({row})row).{column.Name},");
            builder.AppendLine($"                        SetValue = static (row, value) => global::System.Runtime.CompilerServices.Unsafe.Unbox<{row}>(row).{column.Name} = ({column.ClrFqn})value,");
            builder.AppendLine("                    },");
        }

        builder.AppendLine("                },");
        builder.AppendLine($"                isPublic: {(table.IsPublic ? "true" : "false")},");
        builder.AppendLine($"                tier: global::MelangeDB.StorageTier.{table.Tier},");
        builder.AppendLine($"                residency: global::MelangeDB.Residency.{table.Residency},");
        builder.AppendLine($"                placement: global::MelangeDB.Placement.{table.Placement},");
        builder.AppendLine($"                shardBy: {(table.ShardBy is null ? "null" : Literal(table.ShardBy))},");
        builder.AppendLine($"                scheduled: {(table.Scheduled is null ? "null" : Literal(table.Scheduled))},");
        builder.AppendLine("                codec: Instance);");
        builder.AppendLine();
    }

    private static void EmitAccessors(StringBuilder builder, TableModel table)
    {
        var row = table.TypeFqn;
        var handle = $"{table.TypeName}Handle";
        builder.AppendLine($"    /// <summary>Typed access to table '{table.TableName}' through the transactional view.</summary>");
        builder.AppendLine($"    internal readonly struct {handle}");
        builder.AppendLine("    {");
        builder.AppendLine("        private readonly global::MelangeDB.IDbView _db;");
        builder.AppendLine();
        builder.AppendLine($"        public {handle}(global::MelangeDB.IDbView db) => _db = db;");
        builder.AppendLine();
        builder.AppendLine($"        public {row} Insert({row} row) => _db.Insert(row);");
        builder.AppendLine();
        builder.AppendLine($"        public void Update({row} row) => _db.Update(row);");
        builder.AppendLine();
        builder.AppendLine($"        public global::System.Collections.Generic.IEnumerable<{row}> Iter() => _db.Scan<{row}>();");
        foreach (var column in table.Columns.Items)
        {
            if (column.IsKeyEncodable && (column.IsPrimaryKey || column.HasIndexAccessor))
            {
                builder.AppendLine();
                builder.AppendLine($"        public {table.TypeName}{column.Name}Accessor {column.Name} => new {table.TypeName}{column.Name}Accessor(_db);");
            }
        }

        builder.AppendLine("    }");

        foreach (var column in table.Columns.Items)
        {
            if (!column.IsKeyEncodable || !(column.IsPrimaryKey || column.HasIndexAccessor))
                continue;
            var accessor = $"{table.TypeName}{column.Name}Accessor";
            builder.AppendLine();
            builder.AppendLine($"    /// <summary>Typed lookups on '{table.TableName}.{column.Name}'.</summary>");
            builder.AppendLine($"    internal readonly struct {accessor}");
            builder.AppendLine("    {");
            builder.AppendLine("        private readonly global::MelangeDB.IDbView _db;");
            builder.AppendLine();
            builder.AppendLine($"        public {accessor}(global::MelangeDB.IDbView db) => _db = db;");
            if (column.IsPrimaryKey)
            {
                builder.AppendLine();
                builder.AppendLine($"        public {row}? Find({column.ClrFqn} key) => _db.Find<{row}>(key);");
                builder.AppendLine();
                builder.AppendLine($"        public bool Delete({column.ClrFqn} key) => _db.Delete<{row}>(key);");
            }
            else if (column.IsUnique)
            {
                builder.AppendLine();
                builder.AppendLine($"        public {row}? Find({column.ClrFqn} value)");
                builder.AppendLine("        {");
                builder.AppendLine($"            foreach (var row in _db.Filter<{row}>({Literal(column.Name)}, value))");
                builder.AppendLine("                return row;");
                builder.AppendLine("            return null;");
                builder.AppendLine("        }");
            }
            else
            {
                builder.AppendLine();
                builder.AppendLine($"        public global::System.Collections.Generic.IEnumerable<{row}> Filter({column.ClrFqn} value) =>");
                builder.AppendLine($"            _db.Filter<{row}>({Literal(column.Name)}, value);");
                builder.AppendLine();
                builder.AppendLine($"        public global::System.Collections.Generic.IEnumerable<{row}> Filter({column.ClrFqn} low, {column.ClrFqn} high) =>");
                builder.AppendLine($"            _db.FilterRange<{row}>({Literal(column.Name)}, low, high);");
            }

            builder.AppendLine("    }");
        }
    }

    private static void EmitDescriptor(StringBuilder builder, ReducerModel reducer, IReadOnlyDictionary<string, string> tableTypeNames)
    {
        builder.AppendLine("                new global::MelangeDB.Core.ReducerDescriptor(");
        builder.AppendLine($"                    {Literal(reducer.ReducerName)},");
        builder.AppendLine($"                    global::MelangeDB.ReducerKind.{reducer.Kind},");
        builder.AppendLine($"                    typeof({reducer.ContainingTypeFqn}),");
        builder.AppendLine("                    static (ref global::MelangeDB.Core.ReducerArgsReader reader) =>");
        builder.AppendLine("                    {");
        builder.AppendLine($"                        reader.ExpectCount({reducer.Parameters.Length});");
        for (var i = 0; i < reducer.Parameters.Length; i++)
            EmitArgumentRead(builder, reducer.Parameters[i], i, "                        ", bind: false, tableTypeNames);
        builder.AppendLine("                        reader.End();");
        builder.AppendLine("                    },");
        builder.AppendLine("                    static (object instance, global::MelangeDB.ReducerContext context, ref global::MelangeDB.Core.ReducerArgsReader reader) =>");
        builder.AppendLine("                    {");
        builder.AppendLine($"                        reader.ExpectCount({reducer.Parameters.Length});");
        for (var i = 0; i < reducer.Parameters.Length; i++)
            EmitArgumentRead(builder, reducer.Parameters[i], i, "                        ", bind: true, tableTypeNames);
        var arguments = string.Concat(Enumerable.Range(0, reducer.Parameters.Length).Select(static i => $", arg{i}"));
        builder.AppendLine($"                        (({reducer.ContainingTypeFqn})instance).{reducer.MethodName}(context{arguments});");
        builder.AppendLine("                        reader.End();");
        if (reducer.PolicyFqn is null)
        {
            builder.AppendLine("                    }),");
        }
        else
        {
            builder.AppendLine("                    },");
            builder.AppendLine($"                    policy: typeof({reducer.PolicyFqn})),");
        }
    }

    private static void EmitArgumentRead(
        StringBuilder builder,
        ParameterModel parameter,
        int index,
        string indent,
        bool bind,
        IReadOnlyDictionary<string, string> tableTypeNames)
    {
        if (parameter.IsTimerRow)
        {
            // The timer row travels as one blob argument: the scheduler encodes the stored row
            // bytes, and the table's own codec decodes them — the same v1 format as the store.
            if (bind)
            {
                builder.AppendLine($"{indent}var raw{index} = reader.ReadByteArray() ?? throw new global::MelangeDB.Core.ReducerArgumentException(\"The timer-row argument is null.\");");
                builder.AppendLine($"{indent}var arg{index} = global::MelangeDB.Generated.{tableTypeNames[parameter.ClrFqn]}Codec.Instance.Deserialize(raw{index});");
            }
            else
            {
                builder.AppendLine($"{indent}_ = reader.ReadByteArray();");
            }

            return;
        }

        if (!parameter.IsArray)
        {
            var read = ArgRead(parameter.Kind);
            var expression = parameter.IsEnum ? $"({parameter.ClrFqn})reader.{read}()" : $"reader.{read}()";
            builder.AppendLine(bind
                ? $"{indent}var arg{index} = {expression};"
                : $"{indent}_ = {expression};");
            return;
        }

        var elementRead = ArgRead(parameter.ElementKind);
        var elementExpression = parameter.ElementIsEnum
            ? $"({parameter.ElementClrFqn})reader.{elementRead}()"
            : $"reader.{elementRead}()";
        if (bind)
        {
            builder.AppendLine($"{indent}{parameter.ElementClrFqn}[] arg{index} = null;");
            builder.AppendLine($"{indent}var count{index} = reader.BeginArray();");
            builder.AppendLine($"{indent}if (count{index} >= 0)");
            builder.AppendLine($"{indent}{{");
            builder.AppendLine($"{indent}    arg{index} = new {parameter.ElementClrFqn}[count{index}];");
            builder.AppendLine($"{indent}    for (var i{index} = 0; i{index} < count{index}; i{index}++)");
            builder.AppendLine($"{indent}        arg{index}[i{index}] = {elementExpression};");
            builder.AppendLine($"{indent}}}");
        }
        else
        {
            builder.AppendLine($"{indent}var count{index} = reader.BeginArray();");
            builder.AppendLine($"{indent}for (var i{index} = 0; i{index} < count{index}; i{index}++)");
            builder.AppendLine($"{indent}    _ = {elementExpression};");
        }
    }

    private static string ArgRead(WireKind kind) => kind == WireKind.Bytes ? "ReadByteArray" : $"Read{kind}";

    private static string CastToWire(ColumnModel column, string access) =>
        column.IsEnum ? $"({UnderlyingFqn(column.Kind)}){access}" : access;

    private static string CastFromWire(ColumnModel column, string readExpression) =>
        column.IsEnum ? $"({column.ClrFqn}){readExpression}" : readExpression;

    private static string KeyEncode(ColumnModel column, string access) =>
        $"global::MelangeDB.Core.KeyCodec.Encode{column.Kind}({CastToWire(column, access)})";

    private static string UnderlyingFqn(WireKind kind) => kind switch
    {
        WireKind.Int8 => "global::System.SByte",
        WireKind.UInt8 => "global::System.Byte",
        WireKind.Int16 => "global::System.Int16",
        WireKind.UInt16 => "global::System.UInt16",
        WireKind.Int32 => "global::System.Int32",
        WireKind.UInt32 => "global::System.UInt32",
        WireKind.Int64 => "global::System.Int64",
        WireKind.UInt64 => "global::System.UInt64",
        _ => "global::System.Int32",
    };

    private static string Literal(string value)
    {
        var builder = new StringBuilder("\"");
        foreach (var c in value)
        {
            switch (c)
            {
                case '\\':
                    builder.Append("\\\\");
                    break;
                case '"':
                    builder.Append("\\\"");
                    break;
                default:
                    builder.Append(c);
                    break;
            }
        }

        return builder.Append('"').ToString();
    }
}
