using System.Security.Cryptography;
using System.Text;

namespace MelangeDB.CodeGen;

/// <summary>
/// Builds the client-visible schema manifest — the JSON contract a client compilation generates
/// typed bindings from — and the generated source that embeds it in the module assembly. The
/// manifest carries exactly what crosses the wire: public tables minus their <c>[ServerOnly]</c>
/// columns, the enums those surfaces reference, and the client-callable reducer signatures.
/// Format documented in docs/CLIENT-BINDINGS.md; the shape is public API.
/// </summary>
internal static class ManifestEmitter
{
    /// <summary>The manifest format this generator writes; readers reject what they don't know.</summary>
    public const int FormatVersion = 1;

    /// <summary>The well-known generated holder type the exporter and the dev endpoint read.</summary>
    public const string HolderTypeName = "MelangeDB.Generated.MelangeSchemaManifest";

    /// <summary>
    /// Whether the module has a client-visible surface at all. A module of private tables and
    /// lifecycle reducers exports nothing — there is nothing a client could bind to.
    /// </summary>
    public static bool HasClientSurface(TableModel[] tables, ReducerModel[] reducers) =>
        tables.Any(static t => t.IsPublic) || reducers.Any(IsClientCallable);

    /// <summary>
    /// Standard reducers only: lifecycle reducers are fired by the transport, never by a client
    /// call, and a timer-row reducer's argument is the server codec's own row bytes — a client
    /// has no legitimate way to construct it, so no stub should invite the attempt.
    /// </summary>
    public static bool IsClientCallable(ReducerModel reducer) =>
        reducer.Kind == "Standard" && !reducer.HasTimerRowParameter;

    /// <summary>Builds the manifest JSON and its schema hash for an already-ordered model.</summary>
    public static (string Json, string Hash) Build(string module, TableModel[] tables, ReducerModel[] reducers)
    {
        var withoutHash = Render(module, tables, reducers, schemaHash: string.Empty);
        var hash = Sha256Hex(withoutHash);
        return (Render(module, tables, reducers, hash), hash);
    }

    /// <summary>Emits the generated source embedding the manifest verbatim.</summary>
    public static string EmitHolder(string json, string hash)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("// Generated by MelangeDB.CodeGen. Changes will be overwritten.");
        builder.AppendLine("#nullable disable");
        builder.AppendLine("#pragma warning disable");
        builder.AppendLine();
        builder.AppendLine("namespace MelangeDB.Generated");
        builder.AppendLine("{");
        builder.AppendLine("    /// <summary>");
        builder.AppendLine("    /// The client-visible schema this module exports: what tools/MelangeDB.SchemaExport");
        builder.AppendLine("    /// writes to melange-schema.json and the development schema endpoint serves.");
        builder.AppendLine("    /// </summary>");
        builder.AppendLine("    internal static class MelangeSchemaManifest");
        builder.AppendLine("    {");
        builder.AppendLine("        /// <summary>SHA-256 over the manifest JSON rendered with an empty schemaHash field.</summary>");
        builder.AppendLine($"        public const string Hash = \"{hash}\";");
        builder.AppendLine();
        builder.AppendLine("        /// <summary>The manifest JSON, verbatim.</summary>");
        builder.AppendLine($"        public const string Json = @\"{json.Replace("\"", "\"\"")}\";");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static string Render(string module, TableModel[] tables, ReducerModel[] reducers, string schemaHash)
    {
        var publicTables = tables.Where(static t => t.IsPublic).ToArray();
        var clientReducers = reducers.Where(IsClientCallable).ToArray();
        var enums = CollectReferencedEnums(publicTables, clientReducers);

        var json = new JsonBuilder();
        json.BeginObject();
        json.Number("format", FormatVersion);
        json.String("generator", GeneratorVersion());
        json.String("schemaHash", schemaHash);
        json.String("module", module);

        json.BeginArray("enums");
        foreach (var declaration in enums)
        {
            json.BeginObject();
            json.String("name", declaration.Name);
            json.String("underlying", declaration.Underlying.ToString());
            json.BeginArray("members");
            foreach (var member in declaration.Members.Items)
            {
                json.BeginObject();
                json.String("name", member.Name);
                json.String("value", member.Value);
                json.EndObject();
            }

            json.EndArray();
            json.EndObject();
        }

        json.EndArray();

        json.BeginArray("tables");
        foreach (var table in publicTables)
        {
            json.BeginObject();
            json.String("name", table.TableName);
            json.String("type", table.TypeName);
            json.BeginArray("columns");
            foreach (var column in table.Columns.Items)
            {
                if (column.IsServerOnly)
                    continue;
                json.BeginObject();
                json.String("name", column.Name);
                json.String("kind", column.Kind.ToString());
                if (column.IsEnum)
                    json.String("enum", EnumNameOf(enums, column.ClrFqn));
                json.Bool("primaryKey", column.IsPrimaryKey);
                json.Bool("autoInc", column.IsAutoInc);
                json.Bool("unique", column.IsUnique);
                json.Bool("indexed", column.IsIndexed);
                json.EndObject();
            }

            json.EndArray();
            json.EndObject();
        }

        json.EndArray();

        json.BeginArray("reducers");
        foreach (var reducer in clientReducers)
        {
            json.BeginObject();
            json.String("name", reducer.ReducerName);
            json.BeginArray("params");
            foreach (var parameter in reducer.Parameters.Items)
            {
                json.BeginObject();
                json.String("name", parameter.Name);
                json.String("kind", (parameter.IsArray ? parameter.ElementKind : parameter.Kind).ToString());
                json.Bool("isArray", parameter.IsArray);
                if (parameter.IsEnum)
                    json.String("enum", EnumNameOf(enums, parameter.ClrFqn));
                else if (parameter.ElementIsEnum)
                    json.String("enum", EnumNameOf(enums, parameter.ElementClrFqn));
                json.EndObject();
            }

            json.EndArray();
            json.EndObject();
        }

        json.EndArray();
        json.EndObject();
        return json.ToString();
    }

    /// <summary>
    /// The enums the client-visible surface actually references, by name — an enum used only by a
    /// private table or a <c>[ServerOnly]</c> column never leaves the server, so it never ships.
    /// </summary>
    private static EnumModel[] CollectReferencedEnums(TableModel[] publicTables, ReducerModel[] clientReducers)
    {
        var referenced = new HashSet<string>(StringComparer.Ordinal);
        foreach (var table in publicTables)
        {
            foreach (var column in table.Columns.Items)
            {
                if (column is { IsEnum: true, IsServerOnly: false })
                    referenced.Add(column.ClrFqn);
            }
        }

        foreach (var reducer in clientReducers)
        {
            foreach (var parameter in reducer.Parameters.Items)
            {
                if (parameter.IsEnum)
                    referenced.Add(parameter.ClrFqn);
                if (parameter.ElementIsEnum)
                    referenced.Add(parameter.ElementClrFqn);
            }
        }

        var byFqn = new Dictionary<string, EnumModel>(StringComparer.Ordinal);
        foreach (var declaration in publicTables.SelectMany(static t => t.Enums.Items)
            .Concat(clientReducers.SelectMany(static r => r.Enums.Items)))
        {
            if (referenced.Contains(declaration.Fqn) && !byFqn.ContainsKey(declaration.Fqn))
                byFqn[declaration.Fqn] = declaration;
        }

        return [.. byFqn.Values.OrderBy(static e => e.Name, StringComparer.Ordinal)];
    }

    /// <summary>
    /// Names colliding across namespaces cannot be represented — the manifest keys enums by
    /// simple name because that is the name the client bindings declare. Returns the collisions
    /// so the generator can refuse loudly instead of shipping an ambiguous contract.
    /// </summary>
    public static string[] EnumNameCollisions(TableModel[] tables, ReducerModel[] reducers)
    {
        var publicTables = tables.Where(static t => t.IsPublic).ToArray();
        var clientReducers = reducers.Where(IsClientCallable).ToArray();
        return CollectReferencedEnums(publicTables, clientReducers)
            .GroupBy(static e => e.Name, StringComparer.Ordinal)
            .Where(static g => g.Count() > 1)
            .Select(static g => $"{g.Key} ({string.Join(", ", g.Select(static e => e.Fqn))})")
            .ToArray();
    }

    private static string EnumNameOf(EnumModel[] enums, string fqn) =>
        enums.First(e => e.Fqn == fqn).Name;

    private static string GeneratorVersion() =>
        typeof(ManifestEmitter).Assembly.GetName().Version?.ToString() ?? "0.0.0.0";

    private static string Sha256Hex(string text)
    {
        using var sha = SHA256.Create();
        var digest = sha.ComputeHash(Encoding.UTF8.GetBytes(text));
        var hex = new StringBuilder(digest.Length * 2);
        foreach (var b in digest)
            hex.Append(b.ToString("x2", System.Globalization.CultureInfo.InvariantCulture));
        return hex.ToString();
    }

    /// <summary>
    /// A deliberately small JSON writer: two-space indentation, ordinal ordering left to the
    /// caller, strings escaped per RFC 8259. Hand-rolled because the generator targets
    /// netstandard2.0 and ships no dependencies.
    /// </summary>
    private sealed class JsonBuilder
    {
        private readonly StringBuilder _text = new();
        private readonly List<bool> _hasItems = [];
        private int _depth;

        public void BeginObject(string? name = null) => Open('{', name);

        public void EndObject() => Close('}');

        public void BeginArray(string? name = null) => Open('[', name);

        public void EndArray() => Close(']');

        public void String(string name, string value)
        {
            Prefix(name);
            WriteString(value);
        }

        public void Number(string name, long value)
        {
            Prefix(name);
            _text.Append(value.ToString(System.Globalization.CultureInfo.InvariantCulture));
        }

        public void Bool(string name, bool value)
        {
            Prefix(name);
            _text.Append(value ? "true" : "false");
        }

        public override string ToString() => _text.ToString();

        private void Open(char bracket, string? name)
        {
            if (name is not null)
            {
                Prefix(name);
            }
            else if (_depth > 0)
            {
                Separate();
                _text.AppendLine();
                Indent();
            }

            _text.Append(bracket);
            _hasItems.Add(false);
            _depth++;
        }

        private void Close(char bracket)
        {
            var hadItems = _hasItems[_hasItems.Count - 1];
            _hasItems.RemoveAt(_hasItems.Count - 1);
            _depth--;
            if (hadItems)
            {
                _text.AppendLine();
                Indent();
            }

            _text.Append(bracket);
        }

        private void Prefix(string name)
        {
            Separate();
            _text.AppendLine();
            Indent();
            WriteString(name);
            _text.Append(": ");
        }

        private void Separate()
        {
            if (_hasItems.Count == 0)
                return;
            if (_hasItems[_hasItems.Count - 1])
                _text.Append(',');
            else
                _hasItems[_hasItems.Count - 1] = true;
        }

        private void Indent() => _text.Append(' ', _depth * 2);

        private void WriteString(string value)
        {
            _text.Append('"');
            foreach (var c in value)
            {
                switch (c)
                {
                    case '"':
                        _text.Append("\\\"");
                        break;
                    case '\\':
                        _text.Append("\\\\");
                        break;
                    case '\b':
                        _text.Append("\\b");
                        break;
                    case '\f':
                        _text.Append("\\f");
                        break;
                    case '\n':
                        _text.Append("\\n");
                        break;
                    case '\r':
                        _text.Append("\\r");
                        break;
                    case '\t':
                        _text.Append("\\t");
                        break;
                    default:
                        if (c < ' ')
                            _text.Append("\\u").Append(((int)c).ToString("x4", System.Globalization.CultureInfo.InvariantCulture));
                        else
                            _text.Append(c);
                        break;
                }
            }

            _text.Append('"');
        }
    }
}
