// <auto-generated/>
// Generated by MelangeDB.CodeGen from melange-schema.json. Changes will be overwritten.
#nullable disable
#pragma warning disable
namespace MelangeDB.Types
{
    /// <summary>One row of table 'Creature', as the wire carries it to clients.</summary>
    public partial struct Creature
    {
        public ulong Id;
        public ushort ChunkId;
        public Species Kind;
        public float X;
        public string Name;
        public byte[] Genome;
    }

    /// <summary>Decodes 'Creature' rows straight from the wire's row bytes: positional, no dictionary, no boxing.</summary>
    public sealed class CreatureRowCodec : global::MelangeDB.Client.IClientRowCodec<Creature>
    {
        public static readonly CreatureRowCodec Instance = new CreatureRowCodec();

        // The shape these bindings were generated from, compared against the server's
        // descriptor once per subscription. Order is contract: the row bytes are positional.
        private static readonly global::MelangeDB.Protocol.WireColumn[] Shape = new global::MelangeDB.Protocol.WireColumn[]
        {
            new global::MelangeDB.Protocol.WireColumn("Id", global::MelangeDB.ColumnKind.UInt64),
            new global::MelangeDB.Protocol.WireColumn("ChunkId", global::MelangeDB.ColumnKind.UInt16),
            new global::MelangeDB.Protocol.WireColumn("Kind", global::MelangeDB.ColumnKind.Int32),
            new global::MelangeDB.Protocol.WireColumn("X", global::MelangeDB.ColumnKind.Float32),
            new global::MelangeDB.Protocol.WireColumn("Name", global::MelangeDB.ColumnKind.String),
            new global::MelangeDB.Protocol.WireColumn("Genome", global::MelangeDB.ColumnKind.Bytes),
        };

        public string TableName => "Creature";

        public global::System.Collections.Generic.IReadOnlyList<global::MelangeDB.Protocol.WireColumn> Columns => Shape;

        public Creature DecodeRow(global::System.ReadOnlySpan<byte> data)
        {
            var reader = new global::MelangeDB.RowReader(data);
            var row = default(Creature);
            row.Id = reader.ReadUInt64();
            row.ChunkId = reader.ReadUInt16();
            row.Kind = (Species)reader.ReadInt32();
            row.X = reader.ReadFloat32();
            row.Name = reader.ReadString();
            row.Genome = reader.ReadBytes();
            return row;
        }

        public byte[] EncodePrimaryKey(in Creature row) =>
            global::MelangeDB.KeyCodec.EncodeUInt64(row.Id).ToArray();
    }

    /// <summary>Typed access to the 'Creature' client cache: rows, events, lookups, subscriptions.</summary>
    public readonly struct CreatureTableHandle
    {
        private readonly global::MelangeDB.Client.ClientCacheRegistry _caches;
        private readonly global::MelangeDB.Client.ClientCache<Creature> _cache;

        public CreatureTableHandle(global::MelangeDB.Client.ClientCacheRegistry caches)
        {
            _caches = caches;
            _cache = caches.GetOrAdd(CreatureRowCodec.Instance);
        }

        /// <summary>The merged cache under this handle, for advanced use.</summary>
        public global::MelangeDB.Client.ClientCache<Creature> Cache => _cache;

        public event global::System.Action<Creature> OnInsert
        {
            add => _cache.OnInsert += value;
            remove => _cache.OnInsert -= value;
        }

        public event global::System.Action<Creature, Creature> OnUpdate
        {
            add => _cache.OnUpdate += value;
            remove => _cache.OnUpdate -= value;
        }

        public event global::System.Action<Creature> OnDelete
        {
            add => _cache.OnDelete += value;
            remove => _cache.OnDelete -= value;
        }

        /// <summary>Locally cached row count — the rows this client's subscriptions cover, not the table's.</summary>
        public int Count => _cache.Count;

        /// <summary>A snapshot of the locally cached rows.</summary>
        public global::System.Collections.Generic.IReadOnlyList<Creature> Iter() => _cache.Rows;

        /// <summary>Subscribes to every row of 'Creature'.</summary>
        public global::System.Threading.Tasks.Task<global::MelangeDB.Client.TypedSubscription<Creature>> SubscribeAllAsync(global::System.Threading.CancellationToken cancellationToken = default) =>
            _caches.SubscribeAsync(CreatureRowCodec.Instance, "SELECT * FROM Creature", null, cancellationToken);

        public CreatureIdAccessor Id => new CreatureIdAccessor(_caches, _cache);

        public CreatureChunkIdAccessor ChunkId => new CreatureChunkIdAccessor(_caches, _cache);
    }

    /// <summary>Typed lookups and subscriptions on 'Creature.Id', against the local cache and the four query shapes.</summary>
    public readonly struct CreatureIdAccessor
    {
        private readonly global::MelangeDB.Client.ClientCacheRegistry _caches;
        private readonly global::MelangeDB.Client.ClientCache<Creature> _cache;

        public CreatureIdAccessor(global::MelangeDB.Client.ClientCacheRegistry caches, global::MelangeDB.Client.ClientCache<Creature> cache)
        {
            _caches = caches;
            _cache = cache;
        }

        /// <summary>Finds the cached row with this primary key, or null when no subscription covers it.</summary>
        public Creature? Find(ulong key) =>
            _cache.TryFind(global::MelangeDB.KeyCodec.EncodeUInt64(key).ToArray(), out var row) ? row : (Creature?)null;

        /// <summary>Subscribes to rows where 'Id' equals the value.</summary>
        public global::System.Threading.Tasks.Task<global::MelangeDB.Client.TypedSubscription<Creature>> SubscribeAsync(ulong value, global::System.Threading.CancellationToken cancellationToken = default) =>
            _caches.SubscribeAsync(CreatureRowCodec.Instance, "SELECT * FROM Creature WHERE Id = :p", EqualityParameters(value), cancellationToken);

        /// <summary>Re-scopes a subscription created by <see cref="SubscribeAsync(ulong, global::System.Threading.CancellationToken)"/> to a new value, reconciled as a diff.</summary>
        public global::System.Threading.Tasks.Task RescopeAsync(global::MelangeDB.Client.TypedSubscription<Creature> subscription, ulong value, global::System.Threading.CancellationToken cancellationToken = default) =>
            subscription.RescopeAsync(EqualityParameters(value), cancellationToken);

        /// <summary>Subscribes to rows where 'Id' is in [low, high].</summary>
        public global::System.Threading.Tasks.Task<global::MelangeDB.Client.TypedSubscription<Creature>> SubscribeRangeAsync(ulong low, ulong high, global::System.Threading.CancellationToken cancellationToken = default) =>
            _caches.SubscribeAsync(CreatureRowCodec.Instance, "SELECT * FROM Creature WHERE Id BETWEEN :lo AND :hi", RangeParameters(low, high), cancellationToken);

        /// <summary>Re-scopes a subscription created by <see cref="SubscribeRangeAsync(ulong, ulong, global::System.Threading.CancellationToken)"/> to a new window, reconciled as a diff.</summary>
        public global::System.Threading.Tasks.Task RescopeRangeAsync(global::MelangeDB.Client.TypedSubscription<Creature> subscription, ulong low, ulong high, global::System.Threading.CancellationToken cancellationToken = default) =>
            subscription.RescopeAsync(RangeParameters(low, high), cancellationToken);

        private static global::System.Collections.Generic.Dictionary<string, object> EqualityParameters(ulong value) =>
            new global::System.Collections.Generic.Dictionary<string, object> { ["p"] = value };

        private static global::System.Collections.Generic.Dictionary<string, object> RangeParameters(ulong low, ulong high) =>
            new global::System.Collections.Generic.Dictionary<string, object> { ["lo"] = low, ["hi"] = high };
    }

    /// <summary>Typed lookups and subscriptions on 'Creature.ChunkId', against the local cache and the four query shapes.</summary>
    public readonly struct CreatureChunkIdAccessor
    {
        private readonly global::MelangeDB.Client.ClientCacheRegistry _caches;
        private readonly global::MelangeDB.Client.ClientCache<Creature> _cache;

        public CreatureChunkIdAccessor(global::MelangeDB.Client.ClientCacheRegistry caches, global::MelangeDB.Client.ClientCache<Creature> cache)
        {
            _caches = caches;
            _cache = cache;
        }

        /// <summary>The cached rows with this value. Scans the local cache.</summary>
        public global::System.Collections.Generic.List<Creature> Filter(ushort value)
        {
            var key = global::MelangeDB.KeyCodec.EncodeUInt16(value);
            var rows = new global::System.Collections.Generic.List<Creature>();
            foreach (var row in _cache.Rows)
            {
                if (global::MelangeDB.KeyCodec.EncodeUInt16(row.ChunkId) == key)
                    rows.Add(row);
            }

            return rows;
        }

        /// <summary>The cached rows in [low, high], compared exactly as the server compares — by encoded key.</summary>
        public global::System.Collections.Generic.List<Creature> Filter(ushort low, ushort high)
        {
            var lowKey = global::MelangeDB.KeyCodec.EncodeUInt16(low);
            var highKey = global::MelangeDB.KeyCodec.EncodeUInt16(high);
            var rows = new global::System.Collections.Generic.List<Creature>();
            foreach (var row in _cache.Rows)
            {
                var candidate = global::MelangeDB.KeyCodec.EncodeUInt16(row.ChunkId);
                if (candidate.CompareTo(lowKey) >= 0 && candidate.CompareTo(highKey) <= 0)
                    rows.Add(row);
            }

            return rows;
        }

        /// <summary>Subscribes to rows where 'ChunkId' equals the value.</summary>
        public global::System.Threading.Tasks.Task<global::MelangeDB.Client.TypedSubscription<Creature>> SubscribeAsync(ushort value, global::System.Threading.CancellationToken cancellationToken = default) =>
            _caches.SubscribeAsync(CreatureRowCodec.Instance, "SELECT * FROM Creature WHERE ChunkId = :p", EqualityParameters(value), cancellationToken);

        /// <summary>Re-scopes a subscription created by <see cref="SubscribeAsync(ushort, global::System.Threading.CancellationToken)"/> to a new value, reconciled as a diff.</summary>
        public global::System.Threading.Tasks.Task RescopeAsync(global::MelangeDB.Client.TypedSubscription<Creature> subscription, ushort value, global::System.Threading.CancellationToken cancellationToken = default) =>
            subscription.RescopeAsync(EqualityParameters(value), cancellationToken);

        /// <summary>Subscribes to rows where 'ChunkId' is in [low, high].</summary>
        public global::System.Threading.Tasks.Task<global::MelangeDB.Client.TypedSubscription<Creature>> SubscribeRangeAsync(ushort low, ushort high, global::System.Threading.CancellationToken cancellationToken = default) =>
            _caches.SubscribeAsync(CreatureRowCodec.Instance, "SELECT * FROM Creature WHERE ChunkId BETWEEN :lo AND :hi", RangeParameters(low, high), cancellationToken);

        /// <summary>Re-scopes a subscription created by <see cref="SubscribeRangeAsync(ushort, ushort, global::System.Threading.CancellationToken)"/> to a new window, reconciled as a diff.</summary>
        public global::System.Threading.Tasks.Task RescopeRangeAsync(global::MelangeDB.Client.TypedSubscription<Creature> subscription, ushort low, ushort high, global::System.Threading.CancellationToken cancellationToken = default) =>
            subscription.RescopeAsync(RangeParameters(low, high), cancellationToken);

        private static global::System.Collections.Generic.Dictionary<string, object> EqualityParameters(ushort value) =>
            new global::System.Collections.Generic.Dictionary<string, object> { ["p"] = value };

        private static global::System.Collections.Generic.Dictionary<string, object> RangeParameters(ushort low, ushort high) =>
            new global::System.Collections.Generic.Dictionary<string, object> { ["lo"] = low, ["hi"] = high };
    }

}
