// <auto-generated/>
// Generated by MelangeDB.CodeGen. Changes will be overwritten.
#nullable disable
#pragma warning disable
namespace MelangeDB.Generated
{
    /// <summary>Generated serializer for table 'Creature': row format v1, no reflection, no boxing.</summary>
    internal sealed class CreatureCodec : global::MelangeDB.Core.RowCodec<global::Snapshot.Creature>
    {
        public static readonly CreatureCodec Instance = new CreatureCodec();

        public static global::MelangeDB.Core.TableSchema BuildSchema() =>
            new global::MelangeDB.Core.TableSchema(
                typeof(global::Snapshot.Creature),
                "Creature",
                new global::MelangeDB.Core.ColumnSchema[]
                {
                    new global::MelangeDB.Core.ColumnSchema
                    {
                        Name = "Id",
                        ClrType = typeof(ulong),
                        Kind = global::MelangeDB.Core.ColumnKind.UInt64,
                        IsEnum = false,
                        IsPrimaryKey = true,
                        IsAutoInc = true,
                        IsUnique = false,
                        IsIndexed = false,
                        GetValue = static row => ((global::Snapshot.Creature)row).Id,
                        SetValue = static (row, value) => global::System.Runtime.CompilerServices.Unsafe.Unbox<global::Snapshot.Creature>(row).Id = (ulong)value,
                    },
                    new global::MelangeDB.Core.ColumnSchema
                    {
                        Name = "ChunkId",
                        ClrType = typeof(ushort),
                        Kind = global::MelangeDB.Core.ColumnKind.UInt16,
                        IsEnum = false,
                        IsPrimaryKey = false,
                        IsAutoInc = false,
                        IsUnique = false,
                        IsIndexed = true,
                        GetValue = static row => ((global::Snapshot.Creature)row).ChunkId,
                        SetValue = static (row, value) => global::System.Runtime.CompilerServices.Unsafe.Unbox<global::Snapshot.Creature>(row).ChunkId = (ushort)value,
                    },
                    new global::MelangeDB.Core.ColumnSchema
                    {
                        Name = "Kind",
                        ClrType = typeof(global::Snapshot.Species),
                        Kind = global::MelangeDB.Core.ColumnKind.Int32,
                        IsEnum = true,
                        IsPrimaryKey = false,
                        IsAutoInc = false,
                        IsUnique = false,
                        IsIndexed = false,
                        GetValue = static row => ((global::Snapshot.Creature)row).Kind,
                        SetValue = static (row, value) => global::System.Runtime.CompilerServices.Unsafe.Unbox<global::Snapshot.Creature>(row).Kind = (global::Snapshot.Species)value,
                    },
                    new global::MelangeDB.Core.ColumnSchema
                    {
                        Name = "X",
                        ClrType = typeof(float),
                        Kind = global::MelangeDB.Core.ColumnKind.Float32,
                        IsEnum = false,
                        IsPrimaryKey = false,
                        IsAutoInc = false,
                        IsUnique = false,
                        IsIndexed = false,
                        GetValue = static row => ((global::Snapshot.Creature)row).X,
                        SetValue = static (row, value) => global::System.Runtime.CompilerServices.Unsafe.Unbox<global::Snapshot.Creature>(row).X = (float)value,
                    },
                    new global::MelangeDB.Core.ColumnSchema
                    {
                        Name = "Name",
                        ClrType = typeof(string),
                        Kind = global::MelangeDB.Core.ColumnKind.String,
                        IsEnum = false,
                        IsPrimaryKey = false,
                        IsAutoInc = false,
                        IsUnique = false,
                        IsIndexed = false,
                        GetValue = static row => ((global::Snapshot.Creature)row).Name,
                        SetValue = static (row, value) => global::System.Runtime.CompilerServices.Unsafe.Unbox<global::Snapshot.Creature>(row).Name = (string)value,
                    },
                    new global::MelangeDB.Core.ColumnSchema
                    {
                        Name = "Genome",
                        ClrType = typeof(byte[]),
                        Kind = global::MelangeDB.Core.ColumnKind.Bytes,
                        IsEnum = false,
                        IsPrimaryKey = false,
                        IsAutoInc = false,
                        IsUnique = false,
                        IsIndexed = false,
                        GetValue = static row => ((global::Snapshot.Creature)row).Genome,
                        SetValue = static (row, value) => global::System.Runtime.CompilerServices.Unsafe.Unbox<global::Snapshot.Creature>(row).Genome = (byte[])value,
                    },
                },
                isPublic: true,
                tier: global::MelangeDB.StorageTier.Hot,
                residency: global::MelangeDB.Residency.Paged,
                placement: global::MelangeDB.Placement.Partitioned,
                shardBy: "ChunkId",
                scheduled: null,
                codec: Instance);

        public override byte[] Serialize(in global::Snapshot.Creature row)
        {
            var writer = new global::MelangeDB.Core.RowWriter(64);
            writer.WriteUInt64(row.Id);
            writer.WriteUInt16(row.ChunkId);
            writer.WriteInt32((global::System.Int32)row.Kind);
            writer.WriteFloat32(row.X);
            writer.WriteString(row.Name);
            writer.WriteBytes(row.Genome);
            return writer.ToArray();
        }

        public override global::Snapshot.Creature Deserialize(global::System.ReadOnlySpan<byte> data)
        {
            var reader = new global::MelangeDB.Core.RowReader(data);
            var row = default(global::Snapshot.Creature);
            row.Id = reader.ReadUInt64();
            row.ChunkId = reader.ReadUInt16();
            row.Kind = (global::Snapshot.Species)reader.ReadInt32();
            row.X = reader.ReadFloat32();
            row.Name = reader.ReadString();
            row.Genome = reader.ReadBytes();
            return row;
        }

        public override global::MelangeDB.RowKey EncodePrimaryKey(in global::Snapshot.Creature row) =>
            global::MelangeDB.Core.KeyCodec.EncodeUInt64(row.Id);

        public override global::MelangeDB.RowKey? EncodeColumn(string column, in global::Snapshot.Creature row)
        {
            switch (column)
            {
                case "Id": return global::MelangeDB.Core.KeyCodec.EncodeUInt64(row.Id);
                case "ChunkId": return global::MelangeDB.Core.KeyCodec.EncodeUInt16(row.ChunkId);
                default: throw new global::System.ArgumentException($"Table 'Creature' has no key-encodable column '{column}'.", nameof(column));
            }
        }

        public override void AssignAutoInc(ref global::Snapshot.Creature row, global::MelangeDB.Core.AutoIncStage stage, global::MelangeDB.TableId table)
        {
            if (row.Id == 0UL)
                row.Id = stage.Allocate(table);
            else
                stage.ObserveExplicit(table, row.Id);
        }
    }

    /// <summary>Typed access to table 'Creature' through the transactional view.</summary>
    internal readonly struct CreatureHandle
    {
        private readonly global::MelangeDB.IDbView _db;

        public CreatureHandle(global::MelangeDB.IDbView db) => _db = db;

        public global::Snapshot.Creature Insert(global::Snapshot.Creature row) => _db.Insert(row);

        public void Update(global::Snapshot.Creature row) => _db.Update(row);

        public global::System.Collections.Generic.IEnumerable<global::Snapshot.Creature> Iter() => _db.Scan<global::Snapshot.Creature>();

        public CreatureIdAccessor Id => new CreatureIdAccessor(_db);

        public CreatureChunkIdAccessor ChunkId => new CreatureChunkIdAccessor(_db);
    }

    /// <summary>Typed lookups on 'Creature.Id'.</summary>
    internal readonly struct CreatureIdAccessor
    {
        private readonly global::MelangeDB.IDbView _db;

        public CreatureIdAccessor(global::MelangeDB.IDbView db) => _db = db;

        public global::Snapshot.Creature? Find(ulong key) => _db.Find<global::Snapshot.Creature>(key);

        public bool Delete(ulong key) => _db.Delete<global::Snapshot.Creature>(key);
    }

    /// <summary>Typed lookups on 'Creature.ChunkId'.</summary>
    internal readonly struct CreatureChunkIdAccessor
    {
        private readonly global::MelangeDB.IDbView _db;

        public CreatureChunkIdAccessor(global::MelangeDB.IDbView db) => _db = db;

        public global::System.Collections.Generic.IEnumerable<global::Snapshot.Creature> Filter(ushort value) =>
            _db.Filter<global::Snapshot.Creature>("ChunkId", value);

        public global::System.Collections.Generic.IEnumerable<global::Snapshot.Creature> Filter(ushort low, ushort high) =>
            _db.FilterRange<global::Snapshot.Creature>("ChunkId", low, high);
    }
}
