// <auto-generated/>
// Generated by MelangeDB.CodeGen. Changes will be overwritten.
#nullable disable
#pragma warning disable

namespace MelangeDB.Generated
{
    /// <summary>
    /// The client-visible schema this module exports: what tools/MelangeDB.SchemaExport
    /// writes to melange-schema.json and the development schema endpoint serves.
    /// </summary>
    internal static class MelangeSchemaManifest
    {
        /// <summary>SHA-256 over the manifest JSON rendered with an empty schemaHash field.</summary>
        public const string Hash = "35d1eb7e116b591528e66c4e365ca888a5de9ee998f3ded4718b6d309d3e579c";

        /// <summary>The manifest JSON, verbatim.</summary>
        public const string Json = @"{
  ""format"": 1,
  ""generator"": ""0.1.0.0"",
  ""schemaHash"": ""35d1eb7e116b591528e66c4e365ca888a5de9ee998f3ded4718b6d309d3e579c"",
  ""module"": ""MelangeGeneratorTests"",
  ""enums"": [
    {
      ""name"": ""Species"",
      ""underlying"": ""Int32"",
      ""members"": [
        {
          ""name"": ""Wolf"",
          ""value"": ""0""
        },
        {
          ""name"": ""Bear"",
          ""value"": ""1""
        }
      ]
    }
  ],
  ""tables"": [
    {
      ""name"": ""Creature"",
      ""type"": ""Creature"",
      ""columns"": [
        {
          ""name"": ""Id"",
          ""kind"": ""UInt64"",
          ""primaryKey"": true,
          ""autoInc"": true,
          ""unique"": false,
          ""indexed"": false
        },
        {
          ""name"": ""ChunkId"",
          ""kind"": ""UInt16"",
          ""primaryKey"": false,
          ""autoInc"": false,
          ""unique"": false,
          ""indexed"": true
        },
        {
          ""name"": ""Kind"",
          ""kind"": ""Int32"",
          ""enum"": ""Species"",
          ""primaryKey"": false,
          ""autoInc"": false,
          ""unique"": false,
          ""indexed"": false
        },
        {
          ""name"": ""X"",
          ""kind"": ""Float32"",
          ""primaryKey"": false,
          ""autoInc"": false,
          ""unique"": false,
          ""indexed"": false
        },
        {
          ""name"": ""Name"",
          ""kind"": ""String"",
          ""primaryKey"": false,
          ""autoInc"": false,
          ""unique"": false,
          ""indexed"": false
        },
        {
          ""name"": ""Genome"",
          ""kind"": ""Bytes"",
          ""primaryKey"": false,
          ""autoInc"": false,
          ""unique"": false,
          ""indexed"": false
        }
      ]
    }
  ],
  ""reducers"": [
    {
      ""name"": ""Cull"",
      ""params"": []
    },
    {
      ""name"": ""Spawn"",
      ""params"": [
        {
          ""name"": ""chunkId"",
          ""kind"": ""UInt16"",
          ""isArray"": false
        },
        {
          ""name"": ""name"",
          ""kind"": ""String"",
          ""isArray"": false
        },
        {
          ""name"": ""stats"",
          ""kind"": ""Int32"",
          ""isArray"": true
        }
      ]
    }
  ]
}";
    }
}
