// <auto-generated/>
// Generated by MelangeDB.CodeGen. Changes will be overwritten.
#nullable disable
#pragma warning disable
[assembly: global::MelangeDB.Core.MelangeGeneratedModel(typeof(global::MelangeDB.Generated.MelangeModel))]

namespace MelangeDB.Generated
{
    /// <summary>This assembly's tables and reducers, discovered at compile time.</summary>
    internal sealed class MelangeModel : global::MelangeDB.Core.IMelangeModel
    {
        public global::System.Collections.Generic.IReadOnlyList<global::MelangeDB.Core.TableSchema> Tables() =>
            new global::MelangeDB.Core.TableSchema[]
            {
                global::MelangeDB.Generated.CreatureCodec.BuildSchema(),
            };

        public global::System.Collections.Generic.IReadOnlyList<global::MelangeDB.Core.ReducerDescriptor> Reducers() =>
            new global::MelangeDB.Core.ReducerDescriptor[]
            {
                new global::MelangeDB.Core.ReducerDescriptor(
                    "Cull",
                    global::MelangeDB.ReducerKind.Standard,
                    typeof(global::Snapshot.CreatureReducers),
                    static (ref global::MelangeDB.Core.ReducerArgsReader reader) =>
                    {
                        reader.ExpectCount(0);
                        reader.End();
                    },
                    static (object instance, global::MelangeDB.ReducerContext context, ref global::MelangeDB.Core.ReducerArgsReader reader) =>
                    {
                        reader.ExpectCount(0);
                        ((global::Snapshot.CreatureReducers)instance).Cull(context);
                        reader.End();
                    },
                    policy: typeof(global::Snapshot.AdminOnly),
                    site: global::MelangeDB.ReducerSite.Hub),
                new global::MelangeDB.Core.ReducerDescriptor(
                    "Spawn",
                    global::MelangeDB.ReducerKind.Standard,
                    typeof(global::Snapshot.CreatureReducers),
                    static (ref global::MelangeDB.Core.ReducerArgsReader reader) =>
                    {
                        reader.ExpectCount(3);
                        _ = reader.ReadUInt16();
                        _ = reader.ReadString();
                        var count2 = reader.BeginArray();
                        for (var i2 = 0; i2 < count2; i2++)
                            _ = reader.ReadInt32();
                        reader.End();
                    },
                    static (object instance, global::MelangeDB.ReducerContext context, ref global::MelangeDB.Core.ReducerArgsReader reader) =>
                    {
                        reader.ExpectCount(3);
                        var arg0 = reader.ReadUInt16();
                        var arg1 = reader.ReadString();
                        int[] arg2 = null;
                        var count2 = reader.BeginArray();
                        if (count2 >= 0)
                        {
                            arg2 = new int[count2];
                            for (var i2 = 0; i2 < count2; i2++)
                                arg2[i2] = reader.ReadInt32();
                        }
                        ((global::Snapshot.CreatureReducers)instance).Spawn(context, arg0, arg1, arg2);
                        reader.End();
                    },
                    site: global::MelangeDB.ReducerSite.Hub),
            };
    }
}

/// <summary>Typed table accessors on <c>ctx.Db</c>.</summary>
internal static class MelangeDbGeneratedAccessors
{
    extension(global::MelangeDB.IDbView db)
    {
        public global::MelangeDB.Generated.CreatureHandle Creature =>
            new global::MelangeDB.Generated.CreatureHandle(db);
    }
}
