// <auto-generated/>
// Generated by MelangeDB.CodeGen from melange-schema.json. Changes will be overwritten.
#nullable disable
#pragma warning disable
namespace MelangeDB.Types
{
    /// <summary>Mirrors the server's 'Species' enum, per the schema manifest.</summary>
    public enum Species : int
    {
        Wolf = 0,
        Bear = 1,
    }

    /// <summary>The schema these bindings were generated from.</summary>
    public static class MelangeSchema
    {
        /// <summary>The manifest's schema hash; compare against the server module's to surface drift.</summary>
        public const string Hash = "35d1eb7e116b591528e66c4e365ca888a5de9ee998f3ded4718b6d309d3e579c";

        public const string Module = "MelangeGeneratorTests";
    }

    /// <summary>Typed table handles over one connection's merged caches.</summary>
    public sealed class MelangeDbView
    {
        private readonly global::MelangeDB.Client.ClientCacheRegistry _caches;

        internal MelangeDbView(global::MelangeDB.Client.ClientCacheRegistry caches) => _caches = caches;

        public CreatureTableHandle Creature => new CreatureTableHandle(_caches);
    }

    /// <summary>One typed stub per client-callable reducer; the returned LSN is the commit (0 when nothing was written).</summary>
    public sealed class MelangeReducers
    {
        private readonly global::MelangeDB.Client.MelangeClient _client;

        internal MelangeReducers(global::MelangeDB.Client.MelangeClient client) => _client = client;

        public global::System.Threading.Tasks.Task<ulong> CullAsync(global::System.Threading.CancellationToken cancellationToken = default) =>
            _client.CallReducerAsync("Cull", null, cancellationToken);

        public global::System.Threading.Tasks.Task<ulong> SpawnAsync(ushort chunkId, string name, int[] stats, global::System.Threading.CancellationToken cancellationToken = default) =>
            _client.CallReducerAsync("Spawn", new object[] { chunkId, name, stats }, cancellationToken);
    }

    /// <summary>
    /// The typed connection: Db for cached rows and events, Reducers for calls, Client for
    /// everything the raw API still owns (connect, reconnect, untyped subscriptions).
    /// </summary>
    public sealed partial class MelangeConnection
    {
        public MelangeConnection(global::MelangeDB.Client.MelangeClient client)
        {
            Client = client ?? throw new global::System.ArgumentNullException(nameof(client));
            Caches = new global::MelangeDB.Client.ClientCacheRegistry(client);
            Db = new MelangeDbView(Caches);
            Reducers = new MelangeReducers(client);
        }

        public global::MelangeDB.Client.MelangeClient Client { get; }

        public global::MelangeDB.Client.ClientCacheRegistry Caches { get; }

        public MelangeDbView Db { get; }

        public MelangeReducers Reducers { get; }

        /// <summary>The schema hash these bindings were generated from — the drift detector.</summary>
        public string SchemaHash => MelangeSchema.Hash;
    }
}
